/**
 * Build .whissle/context.md from voice session metadata and sync to GitHub.
 *
 * Uses the GitHub Contents API (no Octokit dependency needed):
 *   GET /repos/{owner}/{repo}/contents/{path}   — check if file exists, get SHA
 *   PUT /repos/{owner}/{repo}/contents/{path}    — create/update file
 */

import type { SpeechRate, BehavioralProfile } from "@whissle/live-assist-core";

interface EmotionEntry {
  emotion: string;
  confidence: number;
  offset: number;
}

interface ContextData {
  transcript: Array<{ text: string; channel?: string }>;
  emotionTimeline: EmotionEntry[];
  currentEmotion: string | null;
  currentIntent: string | null;
  speechRate: SpeechRate | null;
  speakerLabel: string | null;
  profile: BehavioralProfile | null;
  sessionDurationMs: number;
}

/** Build a markdown context file from session metadata. */
export function buildContextMarkdown(data: ContextData): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push("# Voice Session Context");
  lines.push("");
  lines.push(`> Auto-generated by Meta-Aware Coding on ${now}`);
  lines.push(`> Session duration: ${Math.round(data.sessionDurationMs / 1000)}s`);
  lines.push("");

  // Emotion summary
  if (data.emotionTimeline.length > 0) {
    const emotionCounts: Record<string, number> = {};
    for (const e of data.emotionTimeline) {
      emotionCounts[e.emotion] = (emotionCounts[e.emotion] || 0) + 1;
    }
    const sorted = Object.entries(emotionCounts).sort((a, b) => b[1] - a[1]);
    const total = data.emotionTimeline.length;

    lines.push("## Emotion Summary");
    lines.push("");
    for (const [emotion, count] of sorted) {
      const pct = Math.round((count / total) * 100);
      lines.push(`- **${emotion}**: ${pct}% (${count} segments)`);
    }
    lines.push("");
  }

  // Speech patterns
  if (data.profile || data.speechRate) {
    lines.push("## Speech Patterns");
    lines.push("");
    if (data.speechRate) {
      lines.push(`- **Speech rate**: ${data.speechRate.words_per_minute} WPM`);
      lines.push(`- **Word count**: ${data.speechRate.word_count}`);
      if (data.speechRate.pause_count > 0) {
        lines.push(`- **Pauses**: ${data.speechRate.pause_count}`);
      }
    }
    if (data.profile) {
      const topEmotion = Object.entries(data.profile.emotionProfile)
        .sort((a, b) => b[1] - a[1])[0];
      if (topEmotion) {
        lines.push(`- **Dominant emotion**: ${topEmotion[0]} (${Math.round(topEmotion[1] * 100)}%)`);
      }
      const topIntent = Object.entries(data.profile.intentProfile)
        .sort((a, b) => b[1] - a[1])[0];
      if (topIntent) {
        lines.push(`- **Primary intent**: ${topIntent[0]} (${Math.round(topIntent[1] * 100)}%)`);
      }
    }
    if (data.currentIntent) {
      lines.push(`- **Last intent**: ${data.currentIntent}`);
    }
    lines.push("");
  }

  // Transcript summary
  if (data.transcript.length > 0) {
    lines.push("## Transcript");
    lines.push("");
    for (const entry of data.transcript.slice(-20)) {
      const prefix = entry.channel === "speaker" ? "[Speaker]" : "[Mic]";
      lines.push(`${prefix} ${entry.text}`);
    }
    lines.push("");
  }

  // Planning cues
  lines.push("## Planning Recommendations");
  lines.push("");
  if (data.currentEmotion === "frustrated" || data.currentEmotion === "angry") {
    lines.push("- User shows frustration — clarify before proceeding");
  } else if (data.currentIntent === "QUERY") {
    lines.push("- User is in exploratory mode — help narrow down options");
  } else if (data.currentIntent === "COMMAND") {
    lines.push("- User is giving direct instructions — execute without asking");
  } else {
    lines.push("- Normal conversational flow — proceed with current approach");
  }
  lines.push("");

  return lines.join("\n");
}

/** Push .whissle/context.md to a GitHub repository. */
export async function syncContextToGitHub(opts: {
  token: string;
  repo: string; // "owner/repo"
  content: string;
  branch?: string;
}): Promise<{ success: boolean; error?: string }> {
  const { token, repo, content, branch = "main" } = opts;
  const path = ".whissle/context.md";
  const apiBase = `https://api.github.com/repos/${repo}/contents/${path}`;
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  try {
    // Check if file already exists (to get SHA for update)
    let sha: string | undefined;
    const getRes = await fetch(`${apiBase}?ref=${branch}`, { headers });
    if (getRes.ok) {
      const existing = await getRes.json();
      sha = existing.sha;
    }

    // Create or update the file
    const body: Record<string, string> = {
      message: "Update voice session context",
      content: btoa(unescape(encodeURIComponent(content))),
      branch,
    };
    if (sha) {
      body.sha = sha;
    }

    const putRes = await fetch(apiBase, {
      method: "PUT",
      headers,
      body: JSON.stringify(body),
    });

    if (!putRes.ok) {
      const err = await putRes.json().catch(() => ({}));
      return {
        success: false,
        error: `GitHub API error ${putRes.status}: ${(err as { message?: string }).message || "Unknown error"}`,
      };
    }

    return { success: true };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
